// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'get-started',
    {
      type: 'category',
      label: 'CODI Resources by Phase',
      collapsed: false,
      link:{
        type: 'doc',
        id: 'codi-resources-by-phase/CODIResourcesByPhase'
      },
      items: [
        {
          type: 'category',
          label: 'Preparation and Planning',
          items: ['codi-resources-by-phase/preparation-and-planning/overview-fact', 'codi-resources-by-phase/preparation-and-planning/collect-store-data-best-practices'],
         
        },
        {
          type: 'category',
          label: 'Implementation',
          items: [
            {
              type: 'category',
              label: 'Data Model',
              items: ['codi-resources-by-phase/implementation/data-model-dictionary', 'codi-resources-by-phase/implementation/data-model-ig', 'codi-resources-by-phase/implementation/structured-data-extract-map-tool'],
            },
            {
              type: 'category',
              label: 'Measuring Impact',
              items: ['codi-resources-by-phase/implementation/dose-services-measure-def', 'codi-resources-by-phase/implementation/diabetes-prevalence-measure-def', 'codi-resources-by-phase/implementation/diabetes-control-measure-def', 'codi-resources-by-phase/implementation/reporting-tool-wireframe-reqs'],
            }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Communities Using CODI',
      collapsed: false,
      link:{
        type: 'doc',
        id: 'communities-using-codi/communities-using-codi'
      },
      items: [
        
        'communities-using-codi/food-insecurity-in-maryland',
        'communities-using-codi/chronic-disease-in-north-carolina',
        'communities-using-codi/childhood-obesity-in-colorado'
      ],
    },
  ],
};

export default sidebars;
